### ISSUE TITLE
Breakup deGov theme into base theme, demo theme, and starterkit

### ISSUE THREAD

**Issue by breidert** [deGov/deGov#10]
At the moment the deGov theme contains specific functionality to theme the deGov features to look like http://demo.degov.de/

This has to be change to on the one hand have sensible basic stylings in place, but on the other hand not to be too specific so sub themeing becomes impossible.

Therefore the deGov theme needs to be broken up into three seperate themes:

- deGov base theme
- deGov demo theme
- deGov starter kit (located in sub folder starterkit in deGov base theme)

The first contains all general settings for example basic layout settings and accessability settings.
The second is a demo implementation that looks like http://demo.degov.de/
The last is a starter theme, that can be used to create an own implementaion of deGov.

All styles need to be broken up into the features we have in deGov. 

Example 1: All general paragraph stylings should reside in a file called paragraphs-general.scss
Example 2: All styles for blog should reside in a file called blog.scss
...

**Comment by breidert** [comment]
The current repository will be turned into two themes:
- degov_base_theme
- degov_demo_theme
The current theme degov_theme will not be used any more.

Each theme will get an additional directory named 'modules' inside of source/sass/. In this directory specific stylings for usecases such as 'blog', 'news', or 'section' go each inside a sub folder. The general styles are kept in the existing structure. The existing sass files should be checked and specific styles should be moved to the modules folder in coresponding sass files such as module/blog/styles.scss.

To distinguish between the degov_base_theme and the degov_demo_theme all layout styles and limited decorational styles stay in the degov_base_theme, all other styles go into the degov_demo_theme.

**Comment by ghost** [comment]
Done. I have also updated the README files with up to date information. Specifically the README.md in the STARTER_KIT contains instructions about how to work with this theme stack.
